dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0

compiler:
  solc:
    version: 0.8.0

networks:
  mainnet:
    eth_usd_price_feed: <ADDRESS>
  kovan:
    eth_usd_price_feed: <ADDRESS>

pinata:
  api_key: ${PINATA_API_KEY}
  api_secret: ${PINATA_API_SECRET}

wallets:
  from_key: ${PRIVATE_KEY}
